###USERS CREATE
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "test1", 
  "email": "test1@test.com",
  "password": "password", 
  "password_confirmatoin": "password"
}

###USER LOGIN ADD JWT IN RESPONSE TO VARIABLE BELOW
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "password"
}

### ADD JWT BELOW TO LOGIN. TO LOGOUT REMOVE JWT TOKEN
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODQyNTUxNDF9.VnObXl21bCpNoUWoFD5k2HS20gd80ZcKzkVPvfVtQ9k

###LIST INDEX
GET http://localhost:3000/lists.json
Authorization: Bearer {{jwt}}

###LIST CREATE
POST http://localhost:3000/lists.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "list_name": "test list"
}

###LIST SHOW
GET http://localhost:3000/lists/1.json

###LIST UPDATE
PATCH http://localhost:3000/lists/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "list_name": "update name"
}

###LIST DESTROY
DELETE http://localhost:3000/lists/1.json
Authorization: Bearer {{jwt}}

###TODO INDEX
GET http://localhost:3000/todos.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "list_id": 2
}

###TODO CREATE
POST http://localhost:3000/todos.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "todo test",
  "details": "detail test",
  "due_date": "whenever",
  "list_id": 1
}

###TODO SHOW
GET http://localhost:3000/todos/1.json

###TODO UPDATE
PATCH http://localhost:3000/todos/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "done": true
}

###TODO DELETE
DELETE http://localhost:3000/todos/9.json
Authorization: Bearer {{jwt}}
