###TODO INDEX
GET http://localhost:3000/todos.json


###TODO CREATE
POST http://localhost:3000/todos.json
Content-Type: application/json

{
  "title": "todo test"
}

###TODO SHOW
GET http://localhost:3000/todos/1.json

###TODO UPDATE
PATCH http://localhost:3000/todos/1.json
Content-Type: application/json

{
  "done": true
}