json.id todo.id
json.title todo.title
json.done todo.done
json.created_at todo.created_at
json.updated_at todo.updated_at
json.user_id todo.user_id
json.details todo.details
json.due_date todo.due_date
json.list_id todo.list_id
